import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TheNavbar from "@/components/layout/TheNavbar";
import TheContainer from "@/components/layout/TheContainer";
import Footer from "@/components/layout/Footer";
import { ClientToaster } from "@/components/layout/TheToast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-gray-50 text-[#212529] flex flex-col min-h-screen w-full overflow-x-hidden`}
      >
        <TheNavbar />
        <TheContainer>
          <ClientToaster />
          {children}
        </TheContainer>

        <Footer />
      </body>
    </html>
  );
}
